# Stage1
FROM node:12-alpine AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . /app
RUN npm run build 
# Stage2
FROM nginx:stable-alpine
# the built files are copied to the nginx folder inside the container to be shared
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
